// src/constants.js

// Dice faces constants
export const DICE_FACES = ['coin', 'diamond', 'swords', 'monkey', 'parrot', 'skull', 'blank'];

// Cards data
export const CARDS = [
    {
        id: 1,
        name: 'Captain',
        description: 'Your score is doubled!',
        hebrewName: 'קברניט',
        hebrewDescription: 'הנקודות מוכפלות!',
        type: 'special',
        effect: 'double_score',
        icon: '👨‍✈️',
    },
    {
        id: 2,
        name: 'Sorceress',
        description: 'You can reroll one skull!',
        hebrewName: 'קוסמת',
        hebrewDescription: 'ניתן להטיל שוב קוביית גולגולת אחת!',
        type: 'special',
        effect: 'reroll_skull',
        icon: '🧙‍♀️',
    },
    {
        id: 3,
        name: 'Treasure Chest',
        description: 'Store dice for safety.',
        hebrewName: 'תיבת האוצר',
        hebrewDescription: 'ניתן לשמור קוביות בבטחה.',
        type: 'special',
        effect: 'store_dice',
        icon: '🧰',
    },
    {
        id: 4,
        name: 'Storm',
        description: 'Only gold and diamonds count. Their value is doubled!',
        hebrewName: 'סופה',
        hebrewDescription: 'רק זהב ויהלומים נחשבים, ערכם מוכפל!',
        type: 'special',
        effect: 'storm',
        icon: '🌪️',
    },
    {
        id: 5,
        name: 'Monkey Business',
        description: 'Monkeys and parrots count together!',
        hebrewName: 'מאנקי ביזנס',
        hebrewDescription: 'קופים ותוכים נספרים יחד!',
        type: 'special',
        effect: 'monkey_business',
        icon: '🐒🦜',
    },
    {
        id: 6,
        name: 'Sea Battle',
        description: 'Collect 1 sword to win bonus points!',
        hebrewName: 'קרב ימי',
        hebrewDescription: 'השג חרב אחת לבונוס!',
        type: 'special',
        effect: 'sea_battle_1',
        icon: '⚔️',
    },
    {
        id: 7,
        name: 'Sea Battle',
        description: 'Collect 2 swords to win bonus points!',
        hebrewName: 'קרב ימי',
        hebrewDescription: 'השג שתי חרבות לבונוס!',
        type: 'special',
        effect: 'sea_battle_2',
        icon: '⚔️⚔️',
    },
    {
        id: 8,
        name: 'Sea Battle',
        description: 'Collect 3 swords to win bonus points!',
        hebrewName: 'קרב ימי',
        hebrewDescription: 'השג שלוש חרבות לבונוס!',
        type: 'special',
        effect: 'sea_battle_3',
        icon: '⚔️⚔️⚔️',
    },
    {
        id: 9,
        name: 'Zombie Attack',
        description: 'Keep rolling until only skulls & swords remain!',
        hebrewName: 'מתקפת זומבים',
        hebrewDescription: 'המשך להטיל עד שיישארו רק חרבות וגולגולות!',
        type: 'special',
        effect: 'zombie_attack',
        icon: '🧟',
    },
    {
        id: 10,
        name: 'Midas Touch',
        description: 'Double the value of coins you collect!',
        hebrewName: 'מגע הזהב',
        hebrewDescription: 'ערך המטבעות מוכפל!',
        type: 'coin',
        effect: 'midas_touch',
        icon: '✨🪙',
    },
    {
        id: 11,
        name: 'Diamond Mine',
        description: 'Triple the value of diamonds you collect!',
        hebrewName: 'מכרה יהלומים',
        hebrewDescription: 'ערך היהלומים משולש!',
        type: 'diamond',
        effect: 'diamond_mine',
        icon: '⛏️💎',
    },
    {
        id: 12,
        name: 'Truce',
        description: 'You must end your turn without swords. If disqualified with swords, you lose 500 points per sword!',
        hebrewName: 'שביתת נשק',
        hebrewDescription: 'חייבים לסיים תור ללא חרבות. אם נפסלים עם חרבות, מאבדים 500 נקודות לכל חרב!',
        type: 'special',
        effect: 'truce',
        icon: '🤝',
    },
    {
        id: 13,
        name: 'Gold',
        description: 'Start your turn with one gold coin.',
        hebrewName: 'זהב',
        hebrewDescription: 'מתחילים את התור עם מטבע זהב אחד.',
        type: 'gold',
        effect: 'start_with_gold',
        icon: '🪙',
    },
    {
        id: 14,
        name: 'Diamond',
        description: 'Start your turn with one diamond.',
        hebrewName: 'יהלום',
        hebrewDescription: 'מתחילים את התור עם יהלום אחד.',
        type: 'diamond',
        effect: 'start_with_diamond',
        icon: '💎',
    },
    {
        id: 15,
        name: 'Skulls',
        description: 'Start your turn with 1 skull.',
        hebrewName: 'גולגולת',
        hebrewDescription: 'מתחילים את התור עם גולגולת אחת.',
        type: 'skull',
        effect: 'start_with_1_skull',
        icon: '💀',
    },
    {
        id: 16,
        name: 'Skulls',
        description: 'Start your turn with 2 skulls.',
        hebrewName: 'גולגולות',
        hebrewDescription: 'מתחילים את התור עם שתי גולגולות.',
        type: 'skull',
        effect: 'start_with_2_skulls',
        icon: '💀💀',
    }

];

// Translations
export const translations = {
    en: {
        title: 'Otzarot Game',
        subtitle: 'The Pirate Treasure Dice Game',
        start_game: 'Start Game',
        reset_game: 'Reset Game',
        roll_dice: 'Roll Dice',
        reroll_selected: 'Roll Selected',
        roll_for_skulls: 'Roll for Skulls',
        end_turn: 'End Turn',
        draw_card: 'Draw Card',
        current_player: 'Current Player',
        phase: 'Phase',
        rolls_remaining: 'Rolls remaining',
        in_skull_island: 'In the Island of Skulls!',
        skull_count: 'skulls',
        game_over: 'Game Over!',
        wins: 'wins!',
        game_log: 'Game Log',
        welcome: 'Welcome to Otzarot!',
        player_setup: 'Player Setup',
        player_name: 'Player Name',
        start: 'Start',
        player_count: 'Number of Players',
        language: 'Language',
        english: 'English',
        hebrew: 'Hebrew',
        click_to_draw: 'Click to Draw a Card',
        waiting_for_card: 'Waiting for Card',
        points: 'points',
        no_skulls_in_island: 'rolled no skulls in the Island of Skulls',
        scored: 'scored',
        with: 'with',
        loses: 'loses',
    },
    he: {
        title: 'אוצרות',
        subtitle: 'משחק קוביות אוצרות הפיראטים',
        start_game: 'התחל משחק',
        reset_game: 'אפס משחק',
        roll_dice: 'הטל קוביות',
        reroll_selected: 'הטל נבחרות',
        roll_for_skulls: 'הטל לגולגולות',
        end_turn: 'סיים תור',
        draw_card: 'שלוף קלף',
        current_player: 'שחקן נוכחי',
        phase: 'שלב',
        rolls_remaining: 'הטלות שנותרו',
        in_skull_island: 'באי הגולגולות!',
        skull_count: 'גולגולות',
        game_over: 'המשחק נגמר!',
        wins: 'ניצח!',
        game_log: 'יומן משחק',
        welcome: 'ברוכים הבאים לאוצרות!',
        player_setup: 'הגדרת שחקנים',
        player_name: 'שם שחקן',
        start: 'התחל',
        player_count: 'מספר שחקנים',
        language: 'שפה',
        english: 'אנגלית',
        hebrew: 'עברית',
        click_to_draw: 'לחץ לשליפת קלף',
        waiting_for_card: 'ממתין לקלף',
        points: 'נקודות',
        no_skulls_in_island: 'לא הטיל גולגולות באי הגולגולות',
        scored: 'השיג',
        with: 'עם',
        loses: 'מאבד',
    },
};

// Common styles
export const styles = {
    container: {
        maxWidth: '800px',
        margin: '0 auto',
        fontFamily: 'Arial, sans-serif',
        color: '#e2e8f0',
        background: 'linear-gradient(to bottom, #0f172a, #1e3a8a)',
        minHeight: '100vh',
        padding: '20px',
    },
    header: {
        textAlign: 'center',
        marginBottom: '20px',
        background: 'linear-gradient(135deg, #1e3a8a, #1e40af)',
        padding: '15px',
        borderRadius: '8px',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.2)',
    },
    headerTitle: {
        color: '#f59e0b',
        margin: '0',
        textShadow: '2px 2px 4px rgba(0, 0, 0, 0.3)',
    },
    gameInfo: {
        display: 'flex',
        justifyContent: 'space-between',
        marginBottom: '20px',
        background: 'linear-gradient(to right, #1e293b, #334155)',
        padding: '15px',
        borderRadius: '8px',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.2)',
    },
    primaryButton: {
        background: 'linear-gradient(to right, #2563eb, #3b82f6)',
        border: 'none',
        borderRadius: '6px',
        padding: '12px 24px',
        color: 'white',
        cursor: 'pointer',
        fontWeight: 'bold',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.2)',
    },
    secondaryButton: {
        background: 'linear-gradient(to right, #eab308, #f59e0b)',
        border: 'none',
        borderRadius: '6px',
        padding: '12px 24px',
        color: '#0f172a',
        cursor: 'pointer',
        fontWeight: 'bold',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.2)',
    },
    dangerButton: {
        background: '#ef4444',
        border: 'none',
        borderRadius: '4px',
        padding: '10px 20px',
        color: 'white',
        cursor: 'pointer',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
    },
    formControl: {
        marginLeft: '10px',
        padding: '8px 12px',
        borderRadius: '4px',
        border: '1px solid #475569',
        background: '#334155',
        color: '#e2e8f0',
    },
    card: {
        background: 'linear-gradient(135deg, #1e293b, #334155)',
        borderRadius: '8px',
        padding: '15px',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
    },
    playerActive: {
        background: 'linear-gradient(135deg, #2563eb, #3b82f6)',
        boxShadow: '0 0 15px rgba(59, 130, 246, 0.5)',
    }
};