name: Deploy to GitHub Pages
on:
  # Trigger on PRs to master
  pull_request:
    branches:
      - master
  # Trigger on pushes to master
  push:
    branches:
      - master
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install terser --save-dev

      # Build PR preview or main based on event type
      - name: Build and prepare deployment
        run: |
          # Store current branch and commit info
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          CURRENT_COMMIT=$(git rev-parse HEAD)

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Build PR preview with staging environment
            STAGING_PATH="/otzarot-game/staging"
            echo "Building PR #${{ github.event.number }} with base path: $STAGING_PATH"
            
            # Build PR version
            NODE_ENV=development \
            VITE_BASE_PATH=$STAGING_PATH \
            VITE_APP_ENV=staging \
            VITE_PR_NUMBER=${{ github.event.number }} \
            VITE_COMMIT_SHA=$CURRENT_COMMIT \
            npm run build
            
            # Create temporary directory for PR build
            mkdir -p tmp-pr-dist
            cp -r dist/* tmp-pr-dist/ || true
            
            # Checkout master in a clean way
            git reset --hard
            git clean -fd
            git fetch origin master:master
            git checkout master
            MAIN_COMMIT=$(git rev-parse HEAD)
            
            # Install dependencies for main branch
            npm ci
            npm install terser --save-dev
            
            # Build main branch with production environment
            NODE_ENV=production \
            VITE_BASE_PATH=/otzarot-game/ \
            VITE_APP_ENV=production \
            VITE_COMMIT_SHA=$MAIN_COMMIT \
            npm run build
            
            # Now, set up the final directory structure with BOTH builds
            # First, make a backup of the main build
            mkdir -p tmp-main-dist
            cp -r dist/* tmp-main-dist/ || true
            
            # Create nested 'staging' directory inside dist and copy PR build there
            mkdir -p dist/staging
            cp -r tmp-pr-dist/* dist/staging/ || true
            
            # Copy back the main build to dist root
            cp -r tmp-main-dist/* dist/ || true
            
            # Create an index.html in staging directory to ensure it can be accessed
            if [ ! -f dist/staging/index.html ]; then
              echo "No index.html found in staging directory, checking if we need to copy it"
              if [ -f tmp-pr-dist/index.html ]; then
                echo "Copying index.html from tmp-pr-dist to staging directory"
                cp tmp-pr-dist/index.html dist/staging/
              fi
            fi
            
            # Print directory structure for verification
            echo "Final dist directory structure:"
            find dist -type f | sort
          else
            # Regular build for master branch
            echo "Building master branch with base path: /otzarot-game/"
            NODE_ENV=production \
            VITE_BASE_PATH=/otzarot-game/ \
            VITE_APP_ENV=production \
            VITE_COMMIT_SHA=$CURRENT_COMMIT \
            npm run build
          fi

          # Print directory structure for debugging
          echo "Final dist directory structure:"
          ls -la dist/

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Add comment on PR with staging link
      - name: Comment on PR with staging link
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 Deployment is ready!

            Visit Staging (PR #${{ github.event.number }}): https://relbns.github.io/otzarot-game/staging

            Visit Production: https://relbns.github.io/otzarot-game
