name: Deploy to GitHub Pages
on:
  # Trigger on PRs to master
  pull_request:
    branches:
      - master
  # Trigger on pushes to master
  push:
    branches:
      - master
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  # PR Preview Build
  build-and-deploy-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install terser --save-dev

      # Create a temporary vite.config.js specifically for the PR build
      - name: Configure vite.config.js for PR
        run: |
          PR_NUMBER="${{ github.event.number }}"
          # Create a backup of the original vite.config.js
          cp vite.config.js vite.config.original.js

          # Use sed to modify the base path in vite.config.js
          sed -i "s|base:.*|base: '/otzarot-game/pr-${PR_NUMBER}/',|" vite.config.js

          # Display the modified config for debugging
          echo "Modified vite.config.js for PR build:"
          cat vite.config.js

      - name: Build PR preview
        run: |
          PR_NUMBER="${{ github.event.number }}"
          echo "Building PR #${PR_NUMBER} preview with base: /otzarot-game/pr-${PR_NUMBER}/"

          NODE_ENV=development \
          npm run build

          # Create a debug file to verify the build
          echo "<html><body><h1>PR #${PR_NUMBER} Preview</h1><p>Built with base: /otzarot-game/pr-${PR_NUMBER}/</p></body></html>" > dist/debug.html

      - name: Deploy PR preview
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          target-folder: pr-${{ github.event.number }}
          clean: true

      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 PR Preview Deployment is ready!

            Visit PR Preview (#${{ github.event.number }}): https://relbns.github.io/otzarot-game/pr-${{ github.event.number }}/

            Visit Production: https://relbns.github.io/otzarot-game/

  # Production Build and Deploy
  build-and-deploy-production:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install terser --save-dev

      # Ensure vite.config.js has the correct base path for production
      - name: Configure vite.config.js for production
        run: |
          # Make a backup of the original config
          cp vite.config.js vite.config.original.js

          # Update the base path for production
          sed -i "s|base:.*|base: '/otzarot-game/',|" vite.config.js

          # Display the modified config for debugging
          echo "Modified vite.config.js for production build:"
          cat vite.config.js

      - name: Build production
        run: |
          NODE_ENV=production \
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
