name: Deploy Test to GitHub Pages
on:
  # Manual trigger only for testing
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-test-files:
    runs-on: ubuntu-latest
    steps:
      - name: Create test directory
        run: |
          mkdir -p test-pages
          # Create a simple test page
          echo '<html><head><title>GitHub Pages Test</title></head><body><h1>GitHub Pages Test</h1><p>This is a simple test page to verify subdirectory deployment.</p></body></html>' > test-pages/index.html
          # Create another test file
          echo '<html><head><title>Test Page 2</title></head><body><h1>Test Page 2</h1><p>This is a second test page.</p><p><a href="index.html">Go back</a></p></body></html>' > test-pages/test2.html
          # List the files to verify
          ls -la test-pages/

      # Deploy to GitHub Pages using the JamesIves action
      - name: Deploy test-pages to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: test-pages
          branch: gh-pages
          target-folder: test-only
          clean: true

      # Output a message with the URL
      - name: Output URL
        run: |
          echo "Test files deployed to: https://relbns.github.io/otzarot-game/test-only/"
