name: Deploy to GitHub Pages
on:
  # Trigger on PRs to master
  pull_request:
    branches:
      - master
  # Trigger on pushes to master
  push:
    branches:
      - master
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  # PR Preview Build
  build-and-deploy-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install terser --save-dev

      # Modify vite.config.js to ensure correct base path
      - name: Update vite.config.js for PR preview
        run: |
          PR_NUMBER="${{ github.event.number }}"
          # Create a backup of the original config
          cp vite.config.js vite.config.original.js

          # Use sed to replace or add the base configuration
          # This ensures the base path is correctly set for GitHub Pages
          if grep -q "base:" vite.config.js; then
            sed -i "s|base:.*|base: '/otzarot-game/pr-${PR_NUMBER}/',|" vite.config.js
          else
            # If base doesn't exist, add it to the defineConfig object
            sed -i "/defineConfig/a\\  base: '/otzarot-game/pr-${PR_NUMBER}/'," vite.config.js
          fi

          echo "Modified vite.config.js:"
          cat vite.config.js

      - name: Build PR preview
        run: |
          PR_NUMBER="${{ github.event.number }}"
          # Export variables that React can access
          export VITE_PR_NUMBER=${PR_NUMBER}
          export VITE_APP_ENV=staging
          export VITE_COMMIT_SHA=$(git rev-parse HEAD)

          # Build with the updated configuration
          npm run build

          # Create a 404.html file to handle client-side routing
          cp dist/index.html dist/404.html

          # Add a debug file to check if deployment works
          echo "<html><body><h1>PR #${PR_NUMBER} Preview</h1><p>Base Path: /otzarot-game/pr-${PR_NUMBER}/</p></body></html>" > dist/debug.html

      - name: Deploy PR preview
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          target-folder: pr-${{ github.event.number }}
          clean: true

      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 PR Preview Deployment is ready!

            Visit PR Preview (#${{ github.event.number }}):
            - Main URL: https://relbns.github.io/otzarot-game/pr-${{ github.event.number }}/
            - Debug page: https://relbns.github.io/otzarot-game/pr-${{ github.event.number }}/debug.html

            Visit Production: https://relbns.github.io/otzarot-game/

  # Production Build and Deploy
  build-and-deploy-production:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install terser --save-dev

      # Ensure vite.config.js has the correct base path for production
      - name: Update vite.config.js for production
        run: |
          # Create a backup of the original config
          cp vite.config.js vite.config.original.js

          # Use sed to replace or add the base configuration
          if grep -q "base:" vite.config.js; then
            sed -i "s|base:.*|base: '/otzarot-game/',|" vite.config.js
          else
            # If base doesn't exist, add it to the defineConfig object
            sed -i "/defineConfig/a\\  base: '/otzarot-game/'," vite.config.js
          fi

          echo "Modified vite.config.js for production:"
          cat vite.config.js

      - name: Build production
        run: |
          # Export variables for the build
          export VITE_APP_ENV=production
          export VITE_COMMIT_SHA=$(git rev-parse HEAD)

          # Build with the updated configuration
          npm run build

          # Create a 404.html file to handle client-side routing
          cp dist/index.html dist/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
