name: Deploy to GitHub Pages

on:
  # Trigger on PRs to master
  pull_request:
    branches:
      - master
  # Trigger on pushes to master
  push:
    branches:
      - master
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Explicitly install Terser
      - name: Install Terser
        run: npm install --save-dev terser

      # Build master branch if it's a push to master or manual trigger
      - name: Build master
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: npm run build

      # If this is a PR, build both master and PR versions
      - name: Fetch and build PR with staging
        if: github.event_name == 'pull_request'
        run: |
          # Store current branch name
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          PR_COMMIT=$(git rev-parse HEAD)

          # First build PR branch with staging environment
          VITE_BASE_PATH=/otzarot-game/staging/ \
          npm run build
          mkdir -p tmp-pr-dist
          mv dist/* tmp-pr-dist/ || true

          # Fetch and checkout master
          git fetch origin master:master
          git checkout master
          MAIN_COMMIT=$(git rev-parse HEAD)

          # Install dependencies again for master branch
          npm ci
          # Install Terser explicitly again
          npm install --save-dev terser

          # Build master branch with production environment
          VITE_BASE_PATH=/otzarot-game/ \
          npm run build

          # Prepare final dist structure
          mkdir -p dist/staging

          # Move PR build to staging directory
          mv tmp-pr-dist/* dist/staging/ || true

          # Print directory structure for debugging
          echo "Final dist directory structure:"
          ls -R dist/

          # Don't fail if any of the copy commands failed
          exit 0

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # Add comment only on PR
      - name: Comment on PR with staging link
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚀 Staging deployment is ready!
            Visit Staging: https://relbns.github.io/otzarot-game/staging/
            (PR #${{ github.event.number }})
            Visit master branch: https://relbns.github.io/otzarot-game/
